### ISSUE TITLE
As mensagens não aparecem no app do telefone

### ISSUE THREAD

**Issue by vicentecandido** [JonasCaetanoSz/maturador-de-chips#1]
Quando há uma troca de mensagens entre os chips, as mensagens "fake" não aparecem no aplicativo do whatsapp.

Este é o comportamento  esperado?

**Comment by JonasCaetanoSz** [comment]
as mensagens não estavam sendo enviadas quando o contato da conta que iria receber a mensagem está salvo. me confirme se o [commit 44effcb]([44effcb](https://github.com/JonasCaetanoSz/maturador-de-chips/commit/44effcbae1f874ba88bead10207b791bb710cc59)l) corrigiu o problema que você citou.
