### ISSUE TITLE
QR code não conecta

### ISSUE THREAD

**Issue by alvoradalunar** [JonasCaetanoSz/maturador-de-chips#2]
Olá, amigo. Tudo bem? Na parte de conectar os números, consigo escanear o QR code tranquilamente, ele chega a carregar por um tempo mas não conecta de fato e acaba carregando a barra mostrando um "desconectando".

E no whatsapp aparece: "Não foi possível conectar-se. Verifique a conexão do seu celular com a internet e escaneie o QR code novamente". Não é a conexão porque consegui conectar tranquilo abrindo uma nova aba no chrome para testar.

Estou usando o arquivo executável, tem noção de alguma solução para isso?

**Comment by JonasCaetanoSz** [comment]
olá, tive esse problema também, a solução que encontrei é fazer o código apagar a pasta **Service Worker**. mas como não funcionou por ai, tente apagar a pasta `C:\Users\%UserProfile%\AppData\Local\Programs\Maturador de Chips\sessions` (você perderá a sessão de todas contas conectadas no programa) e, se mesmo assim não conectar, tente corrigir trocando o **user-agent**

**Comment by alvoradalunar** [comment]
Funcionou perfeitamente, obrigada!!
