### ISSUE TITLE
Maturando somente alguns números.

### ISSUE THREAD

**Issue by estevaolelis** [JonasCaetanoSz/maturador-de-chips#3]
Percebi que as vezes o programa não identifica todos os 10 números, assim ele fica maturando somente alguns.
![disparo](https://github.com/JonasCaetanoSz/maturador-de-chips/assets/58829175/fabd5220-7c5d-46cc-9780-f8588a709a7b)
Esse erro tentarei verificar se consigo te ajudar de alguma forma para solucionar, porque achei muito bem feito seu maturador.

**Comment by JonasCaetanoSz** [comment]
opa Estêvão, se entendi certo qual é o erro, então imagino que o problema esteja relacionado na repetição dos numeros gerados com o [random ](https://docs.python.org/3/library/random.html). oque acontece é que o programa vai escolher a conta que recebe a mensagem de forma pseudo aleatoria, não pegar uma a uma pra receber, então por muitas vezes algumas contas vão ficar sem receber mensagens e outras vezes vão receber mais de 1 mensagem, veja:

```python
import random

rands = []
for i in range(0,50):
    rands.append(random.randint(0,10))
    if len(rands) == 10:
        print(rands)
        rands.clear()
```

essa foi a saida quando executei:

```python

[4, 9, 8, 9, 6, 4, 2, 8, 2, 8]
[3, 2, 10, 5, 6, 4, 0, 10, 3, 7]
[6, 3, 1, 5, 5, 5, 1, 0, 10, 3]
[5, 7, 7, 10, 1, 6, 8, 6, 4, 5]
[4, 5, 10, 7, 7, 7, 1, 3, 4, 7]
```

seguindo o raciocinio, se os numeros da 1° lista fossem os que foram gerados pelo maturador durante execução, então o aquecimento dos chips seriam:

- as contas nas instancias  M02, M04 e M09  receberiam mensagens 2 vezes
- a conta na instancia M06 receberia mensagem 1 vez
- a conta na instancia M08 receberia mensagem 3 vezes
- as contas em M01, M03, M05, M07 e M010 ficariam sem receber mensagem.


mas é possivel fazer ele enviar mensagem para todos os chips excluindo numeros já gerados antes pelo random. porém como todos  os chips receberiam o mesmo numero de mensagens e criariam um padrão para o whatsapp , não tenho certeza se o aquecimento seria eficaz, mas posso te ajudar a fazer essa alteração no codigo e se o numero de ban durante a maturação não aumentar fazemos a alteração na branch principal, ok?

**Comment by estevaolelis** [comment]
Pode ser Jonas. É que seu maturador tem uma parada que é daora é a quantidade de mensagem que cada chip irá enviar. Teve um outro maturador que utilizei, coloquei 10 chips, o primeiro chip dispara primeiro para esses 9. Então os outros sempre recebia uma mensagem mas ele não recebia nenhuma mensagem, então sempre pela quantidade de mensagem enviada. Então eu acho que seria daora ter uma parada randomica desse jeito, principalmente na parte de disparar, mas que pegue todos os números de certa forma.
