### ISSUE TITLE
arquivo de mensagem

### ISSUE THREAD

**Issue by leolfgomes** [JonasCaetanoSz/maturador-de-chips#5]
Ola, primeiramente parabens pelo projeto.
Tenho uma duvida, para enviar as mensagem, tenho que ter ou criar o arquivo de mensagens? se precisar criar como faço isso, e que tipo de arquivo devo criar.

Obrigado

**Comment by JonasCaetanoSz** [comment]
apenas arquivos com extensão **.txt** são aceitos! você pode colocar qualquer coisa no arquivo, seja frases, letra de música e até  roteiro de filme é valido. se você estiver tendo problema com o arquivo de mensagens, é provavelmente erro na codificação do arquivo que não está em utf-8, nesse caso você precisa corrigir isso usando algum editor de texto.
